### ISSUE TITLE
案件4　キャラクターに色を付ける

### ISSUE THREAD

**Issue by kihou** [mwed-study-group/sample_momotaro_static_3#25]
チームで下のように登場人物にそれぞれカラーをつけてください。

【登場人物 色】
★おじいさん  黄土色（ @n-watanabe-mwed 
おばあさん 藤色
バナナ太郎 黄色
ハイエナ    灰色
★チンパンジー   オレンジ（ @kihou
ダチョウ    ピンク
鬼 赤
ひとり一キャラクターずつ、1ページ終わるごとにコミットして、pushしてください。 次のページを始める前には、最新の作業ブランチを反映してください。

**Comment by n-watanabe-mwed** [comment]
25_bananataro

ブランチ名はこちら
